# Generated by Django 3.2.8 on 2022-01-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='has_applied',
            field=models.BooleanField(default=False),
        ),
    ]
