# Generated by Django 4.0.1 on 2022-01-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_userdetail_has_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
