# Generated by Django 3.2.8 on 2022-01-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20220124_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='menu/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='restaurant/'),
        ),
    ]
