# Generated by Django 3.2.5 on 2022-01-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooding', '0002_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Initiated', max_length=10),
        ),
    ]
